// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentinelGear.Data;

#nullable disable

namespace SentinelGear.Data.Migrations
{
    [DbContext(typeof(SentinelGearDbContext))]
    [Migration("20260312192944_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SentinelGear.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SentinelGear.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Protective Gear"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tactical Backpacks"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Field Accessories"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Combat Clothing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Boots"
                        });
                });

            modelBuilder.Entity("SentinelGear.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SentinelGear.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SentinelGear.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Здрава тактическа каска с висока устойчивост.",
                            ImageUrl = "/images/products/tactical_ballistic_helmet.png",
                            IsDeleted = false,
                            Manufacturer = "Sentinel Defense",
                            Name = "Tactical Ballistic Helmet",
                            Price = 249.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Тактическа жилетка с MOLLE система.",
                            ImageUrl = "/images/products/plate_carrier_vest.png",
                            IsDeleted = false,
                            Manufacturer = "Iron Shield",
                            Name = "Plate Carrier Vest",
                            Price = 319.50m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Подсилени тактически ръкавици за защита и сцепление.",
                            ImageUrl = "/images/products/tactical_protective_gloves.png",
                            IsDeleted = false,
                            Manufacturer = "TacCore",
                            Name = "Tactical Protective Gloves",
                            Price = 44.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Раница с голям капацитет за полеви условия.",
                            ImageUrl = "/images/products/recon_tactical_backpack_45L.png",
                            IsDeleted = false,
                            Manufacturer = "FieldOps",
                            Name = "Recon Tactical Backpack 45L",
                            Price = 189.90m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Компактна тактическа раница за ежедневна употреба.",
                            ImageUrl = "/images/products/urban_tactical_backpack_30L.png",
                            IsDeleted = false,
                            Manufacturer = "FieldOps",
                            Name = "Urban Tactical Backpack 30L",
                            Price = 129.99m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Издръжлива раница за дълги мисии.",
                            ImageUrl = "/images/products/heavy_duty_military_backpack_60L.png",
                            IsDeleted = false,
                            Manufacturer = "Iron Shield",
                            Name = "Heavy Duty Military Backpack 60L",
                            Price = 219.50m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Подсумник за инструменти и оборудване.",
                            ImageUrl = "/images/products/compact_utility_pouch.png",
                            IsDeleted = false,
                            Manufacturer = "TacCore",
                            Name = "Compact Utility Pouch",
                            Price = 34.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Здрав колан за носене на оборудване.",
                            ImageUrl = "/images/products/heavy_duty_tactical_belt.png",
                            IsDeleted = false,
                            Manufacturer = "FieldOps",
                            Name = "Heavy Duty Tactical Belt",
                            Price = 49.90m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Мощен LED фенер за тактически операции.",
                            ImageUrl = "/images/products/military_flashlight.png",
                            IsDeleted = false,
                            Manufacturer = "BlackRoute",
                            Name = "Military Flashlight",
                            Price = 59.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Комплект бойно облекло за полеви условия.",
                            ImageUrl = "/images/products/combat_uniform_set.png",
                            IsDeleted = false,
                            Manufacturer = "StrikeWear",
                            Name = "Combat Uniform Set",
                            Price = 139.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Лека тактическа риза с висока издръжливост.",
                            ImageUrl = "/images/products/tactical_combat_shirt.png",
                            IsDeleted = false,
                            Manufacturer = "StrikeWear",
                            Name = "Tactical Combat Shirt",
                            Price = 79.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Тактически панталони с подсилени колена.",
                            ImageUrl = "/images/products/military_tactical_pants.png",
                            IsDeleted = false,
                            Manufacturer = "StrikeWear",
                            Name = "Military Tactical Pants",
                            Price = 99.90m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Тактически обувки с висока стабилност.",
                            ImageUrl = "/images/products/tactical_combat_boots.png",
                            IsDeleted = false,
                            Manufacturer = "BlackRoute",
                            Name = "Tactical Combat Boots",
                            Price = 159.75m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Леки тактически обувки за бързо движение.",
                            ImageUrl = "/images/products/lightweight_tactical_boots.png",
                            IsDeleted = false,
                            Manufacturer = "FieldOps",
                            Name = "Lightweight Tactical Boots",
                            Price = 129.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Водоустойчиви обувки за тежки условия.",
                            ImageUrl = "/images/products/waterproof_military_boots.png",
                            IsDeleted = false,
                            Manufacturer = "Iron Shield",
                            Name = "Waterproof Military Boots",
                            Price = 179.99m,
                            StockQuantity = 14
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentinelGear.Models.CartItem", b =>
                {
                    b.HasOne("SentinelGear.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SentinelGear.Models.OrderItem", b =>
                {
                    b.HasOne("SentinelGear.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelGear.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SentinelGear.Models.Product", b =>
                {
                    b.HasOne("SentinelGear.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SentinelGear.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SentinelGear.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SentinelGear.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
